# Generated by Django 3.0.2 on 2020-03-11 14:01

from django.db import migrations, models
import phone_field.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='id',
        ),
        migrations.AddField(
            model_name='registereduser',
            name='Email',
            field=models.EmailField(default='<youraddress>@domain.com', max_length=254),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='Id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='PhoneNumber',
            field=phone_field.models.PhoneField(blank=True, help_text='Phone Number', max_length=31, null=True, unique=True),
        ),
    ]
