# Generated by Django 3.0.2 on 2020-03-11 14:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200311_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='Id',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
