# Generated by Django 3.0.2 on 2020-03-11 14:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200311_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='Email',
            field=models.EmailField(default='<address>@domain.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='Id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
