# Generated by Django 3.0.4 on 2020-03-11 16:37

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20200311_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='PhoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
